package com.rodr.tourcamp.Contexto;

import android.app.Application;
import android.content.Context;

public class AppFragments extends Application {

    public static Context context; // CONTEXTO....

    // NOMBRE DE LA BASE DE DATOS....
    public static String databaseNameTourCamp = "TourCamp"; // NOMBRE DE LA BASE DE DATOS TourCamp....
    public static int version = 7; // VERSION...

    // TABLA "Usuarios" DE LA BD....
    public static String tbUsuarios = "Usuarios"; // TABLA DE USUARIOS...

    // CAMPOS DE LA TABLA DE USUARIOS DE LA BD...
    public static String tbCorreoUser = "Correo"; // CAMPO Correo PARA LA TABLA USUARIOS...
    public static String tbNombreUser = "Nombre"; // CAMPO Nombre PARA LA TABLA USUARIOS...
    public static String tbApellidoPaternoUser = "Apellido_Paterno"; // CAMPO Apellido_Paterno PARA LA TABLA USUARIOS...
    public static String tbApellidoMaternoUser = "Apellido_Materno"; // CAMPO Apellido_Materno PARA LA TABLA USUARIOS...
    public static String tbGeneroUser = "Genero"; // CAMPO Genero PARA LA TABLA USUARIOS...
    public static String tbContraseniaUser = "Contraseña"; // CAMPO Contraseña PARA LA TABLA USUARIOS...
    public static String tbConfirmarContraseñaUser = "Confirmar_Contraseña"; // CAMPO Confirmar_Contraseña PARA LA TABLA USUARIOS...

    // TABLA "CompraBoleto" EN LA BD.....
    public static String tbCompraBoleto = "CompraBoleto"; // TABLA DE USUARIOS...

    // CAMPOS DE LA TABLA CompraBoleto DE LA BD.....
    public static String tbNombreCompraBoleto = "Nombre"; // CAMPO Nombre PARA LA TABLA CompraBoleto...
    public static String tbApellidoPCompraBoleto = "Apellido_Paterno"; // CAMPO Apellido_Paterno PARA LA TABLA CompraBoleto...
    public static String tbApellidoMCompraBoleto = "Apellido_Materno"; // CAMPO Apellido_Materno PARA LA TABLA CompraBoleto...
    public static String tbNacionalidadCompraBoleto = "Nacionalidad"; // CAMPO Nacionalidad PARA LA TABLA CompraBoleto...
    public static String tbSitioCompraBoleto = "Sitio_Lugar"; // CAMPO Sitio_Lugar PARA LA TABLA CompraBoleto...
    public static String tbFechaCompraBoleto = "Fecha_Visita"; // CAMPO Fecha_Visita PARA LA TABLA CompraBoleto...
    public static String tbHoraCompraBoleto = "Hora_Visita"; // CAMPO Hora_Visita PARA LA TABLA CompraBoleto...
    public static String tbMetodoPagoCompraBoleto = "Metodo_Pago"; // CAMPO Metodo_Pago PARA LA TABLA CompraBoleto...

    @Override
    public void onCreate() {
        super.onCreate();
        context = getApplicationContext(); // OBTENDO MI CONTEXTO....
    }
}
